export { default as AddSomething } from './add-something.png'
export { default as Logo } from './logo.png'
export { default as ScanCamera } from './scan-camera.png'
export { default as SearchingHouse } from './searching-house.png'
export { default as AddressMap } from './address-map.png'
